name: shopping_list
description: Coding Sample Project For Chunky Tofu Studios
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.2
  freezed_annotation: ^2.4.4
  get_it: ^9.2.0
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: ^2.6.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/backgrounds/
    - assets/icons/
    - assets/logos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
